import{a as w,S as g,i}from"./assets/vendor-7439763b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&s(f)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const b="44806240-6b3f320b71171cc3cb97c5da2",v="https://pixabay.com/api/";async function p(r,t=1,n=15){return(await w.get(v,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}let m;function L(r,t){const n=r.map(s=>`
    <div class="gallery-item">
      <a href="${s.largeImageURL}" class="gallery-link">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${s.likes}</p>
        <p>Views: ${s.views}</p>
        <p>Comments: ${s.comments}</p>
        <p>Downloads: ${s.downloads}</p>
      </div>
    </div>
  `).join("");t.insertAdjacentHTML("beforeend",n),m?m.refresh():m=new g(".gallery a",{})}const S=document.querySelector("#search-form"),h=document.querySelector("#gallery"),d=document.querySelector("#loader"),a=document.querySelector("#load-more");let c="",l=1;const u=15;let y;async function q(r){if(r.preventDefault(),c=r.target.elements.query.value.trim(),!c){i.error({title:"Error",message:"Search query cannot be empty!"});return}l=1,d.classList.remove("hidden"),h.innerHTML="",a.classList.add("hidden"),y&&y.destroy();try{const t=await p(c,l,u);t.hits.length===0?i.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):(L(t.hits,h),y=new g(".gallery a",{}),t.totalHits>u&&a.classList.remove("hidden"))}catch(t){console.log(t),i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.classList.add("hidden")}}async function P(){l+=1,d.classList.remove("hidden"),a.classList.add("hidden");try{const r=await p(c,l,u);L(r.hits,h),l*u>=r.totalHits?(a.classList.add("hidden"),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):a.classList.remove("hidden")}catch(r){console.log(r),i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.classList.add("hidden")}}S.addEventListener("submit",q);a.addEventListener("click",P);
//# sourceMappingURL=commonHelpers.js.map
